// app
export const SET_WINDOW_SIZE = 'SET_WINDOW_SIZE';
export const LOAD_NEXT_LEVEL = 'LOAD_NEXT_LEVEL';

// elements
export const SET_GRID_DIMENSIONS = 'SET_GRID_DIMENSIONS';
export const REGISTER_BOXES = 'REGISTER_BOXES';
export const ADD_BOX_CLASS = 'ADD_BOX_CLASS';
export const DELETE_BOX_CLASS = 'DELETE_BOX_CLASS';
export const TOGGLE_BOX_CLASS = 'TOGGLE_BOX_CLASS';
export const ADD_BOX_CLASSES = 'ADD_BOX_CLASSES';
export const DELETE_BOX_CLASSES = 'DELETE_BOX_CLASSES';
export const TOGGLE_BOX_CLASSES = 'TOGGLE_BOX_CLASSES';
export const ADD_ALL_CLASS = 'ADD_ALL_CLASS';
export const DELETE_ALL_CLASS = 'DELETE_ALL_CLASS';
export const TOGGLE_ALL_CLASS = 'TOGGLE_ALL_CLASS';
export const ADD_ALL_CLASSES = 'ADD_ALL_CLASSES';
export const DELETE_ALL_CLASSES = 'DELETE_ALL_CLASSES';
export const TOGGLE_ALL_CLASSES = 'TOGGLE_ALL_CLASSES';
export const SET_SELECTED = 'SET_SELECTED';
export const SHUFFLE_GRID = 'SHUFFLE_GRID';
export const BLANK_ACTION = 'BLANK_ACTION';
export const UPDATE_GRID = 'UPDATE_GRID';
export const UPDATE_BOX = 'UPDATE_BOX';

// simon
export const RESET_SIMON = 'RESET_SIMON';
export const ADD_SIMON_CORRECT = 'ADD_SIMON_CORRECT';
export const INCREMENT_SIMON_TRIES = 'INCREMENT_SIMON_TRIES';
export const UPDATE_SIMON_USER = 'UPDATE_SIMON_USER';
export const SET_SIMON_MAX = 'SET_SIMON_MAX';