// app
export const SET_WINDOW_SIZE = 'SET_WINDOW_SIZE';
export const LOAD_NEXT_SCREEN = 'LOAD_NEXT_SCREEN';

// elements
export const SET_GRID_PADDING = 'SET_GRID_PADDING';
export const REGISTER_BOXES = 'REGISTER_BOXES';
export const ADD_BOX_CLASS = 'ADD_BOX_CLASS';
export const DELETE_BOX_CLASS = 'DELETE_BOX_CLASS';
export const TOGGLE_BOX_CLASS = 'TOGGLE_BOX_CLASS';
export const ADD_ALL_CLASS = 'ADD_ALL_CLASS';
export const DELETE_ALL_CLASS = 'DELETE_ALL_CLASS';
export const TOGGLE_ALL_CLASS = 'TOGGLE_ALL_CLASS';
export const SET_SELECTED = 'SET_SELECTED';
export const SHUFFLE_GRID = 'SHUFFLE_GRID';
export const BLANK_ACTION = 'BLANK_ACTION';